2024-08-25 21:50:04|ERROR|app.py:43|'pid'
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 115, in GET
    shopCfg = Shop.getShopCfg(version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 40, in getShopCfg
    strKey = Config.KEY_SHOP_CFG_INVENTORY.format(product['pid'])
KeyError: 'pid'
2024-08-25 21:53:52|ERROR|app.py:43|'pid'
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 115, in GET
    shopCfg = Shop.getShopCfg(version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 41, in getShopCfg
    strKey = Config.KEY_SHOP_CFG_INVENTORY.format(pid)
KeyError: 'pid'
2024-08-25 21:56:21|ERROR|app.py:43|BasicKeyCommands.get() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 131, in POST
    buyInfo = Shop.shopBuy(userId, propId, buyNum, shopVersion, version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 78, in shopBuy
    money = Lobby.getMoney(userId,paytype)
  File "/home/weihong/backendFrame/webpy/./Lobby.py", line 15, in getMoney
    money = int(Config.grds.get(strKey,paytype))
TypeError: BasicKeyCommands.get() takes 2 positional arguments but 3 were given
2024-08-25 22:06:59|ERROR|app.py:43|(1054, "Unknown column 'paytype' in 'field list'")
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 131, in POST
    buyInfo = Shop.shopBuy(userId, propId, buyNum, shopVersion, version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 99, in shopBuy
    DBManage.updateMoney(userId, paytype, money, now)
  File "/home/weihong/backendFrame/webpy/./DBManage.py", line 40, in updateMoney
    Config.gdb.update(
  File "/usr/local/lib/python3.10/dist-packages/web/db.py", line 1145, in update
    self._db_execute(db_cursor, query)
  File "/usr/local/lib/python3.10/dist-packages/web/db.py", line 764, in _db_execute
    out = cur.execute(query, params)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'paytype' in 'field list'")
2024-08-25 22:14:41|ERROR|app.py:43|'pid'
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 131, in POST
    buyInfo = Shop.shopBuy(userId, propId, buyNum, shopVersion, version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 106, in shopBuy
    inventory = Lobby.getInventory(propId)
  File "/home/weihong/backendFrame/webpy/./Lobby.py", line 41, in getInventory
    strKey = Config.KEY_SHOP_CFG_INVENTORY.format(pid)
KeyError: 'pid'
2024-08-25 22:18:22|ERROR|app.py:43|BasicKeyCommands.get() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "app.py", line 40, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 50, in wrapper
    return func(*args,**kwargs)
  File "app.py", line 131, in POST
    buyInfo = Shop.shopBuy(userId, propId, buyNum, shopVersion, version)
  File "/home/weihong/backendFrame/webpy/./Shop.py", line 106, in shopBuy
    inventory = Lobby.getInventory(propId)
  File "/home/weihong/backendFrame/webpy/./Lobby.py", line 44, in getInventory
    inventory = int(Config.grds.get(strKey,'inventory'))
TypeError: BasicKeyCommands.get() takes 2 positional arguments but 3 were given
